// Core exports
export { GameObject } from './core/GameObject.js';
export { GameEngine } from './core/GameEngine.js';
export type { GameConfig } from './core/GameEngine.js';

// Sprite exports
export type { Sprite, SpriteFrame, SpriteMetadata } from './sprites/SpriteTypes.js';

// Room exports
export type {
    RoomDefinition,
    RoomInstance,
    ViewConfig,
    BackgroundConfig,
} from './rooms/RoomTypes.js';

// Input constants
export {
    vk_nokey,
    vk_anykey,
    vk_left,
    vk_right,
    vk_up,
    vk_down,
    vk_enter,
    vk_escape,
    vk_space,
    vk_shift,
    vk_control,
    vk_alt,
    vk_backspace,
    vk_tab,
    vk_home,
    vk_end,
    vk_delete,
    vk_insert,
    vk_pageup,
    vk_pagedown,
    vk_pause,
    vk_printscreen,
    vk_f1,
    vk_f2,
    vk_f3,
    vk_f4,
    vk_f5,
    vk_f6,
    vk_f7,
    vk_f8,
    vk_f9,
    vk_f10,
    vk_f11,
    vk_f12,
    vk_numpad0,
    vk_numpad1,
    vk_numpad2,
    vk_numpad3,
    vk_numpad4,
    vk_numpad5,
    vk_numpad6,
    vk_numpad7,
    vk_numpad8,
    vk_numpad9,
    vk_multiply,
    vk_divide,
    vk_add,
    vk_subtract,
    vk_decimal,
    vk_a,
    vk_b,
    vk_c,
    vk_d,
    vk_e,
    vk_f,
    vk_g,
    vk_h,
    vk_i,
    vk_j,
    vk_k,
    vk_l,
    vk_m,
    vk_n,
    vk_o,
    vk_p,
    vk_q,
    vk_r,
    vk_s,
    vk_t,
    vk_u,
    vk_v,
    vk_w,
    vk_x,
    vk_y,
    vk_z,
} from './input/KeyboardManager.js';

export { mb_left, mb_right, mb_middle } from './input/MouseManager.js';
